### ISSUE TITLE
Gym busy times showing inconsistent titles

### ISSUE THREAD

**Issue by CameronHamidi** [cuappdev/uplift-ios#138]
The Gym view will display a histogram of open hours and their associated busyness under the "Busy Times" label. Selecting one of the histogram's bars should display a label with the selected time and a message depending on the busyness of that particular time ("Not too busy", "A little busy", or "As busy as it gets").

However, the view currently displays labels inconsistent with the gym's busyness at that particular time, eg it will display "Not too busy" for a certain label, and "A little busy" for both labels with higher and lower busyness. It is worthwhile investigating `Histogram.swift` to see where this error is coming from.

Also take a look at the indexing for labelling the bars, since there appears to be a one-off(?) error.

**Comment by jmf373** [comment]
I suspect this could be an indexing error in the `selectBar` method
