### ISSUE TITLE
Remove habit tracker and pros from HomeViewController

### ISSUE THREAD

**Issue by ywsang** [cuappdev/uplift-ios#148]
Remove these cells from the `HomeViewController` and revert to look like current production version. Will have to:
- remove the relevant sections (habit tracker + pros), but keep the code in a separate folder
- revert to old format for "ALL GYMS", disregarding favorites for now
- add back "I'M LOOKING FOR..." section 

For reference:
Old `HomeController` before the new changes here: https://github.com/cuappdev/uplift-ios/blob/d4a2fdd0398dc28bf533e8c3c8560d936d8eafd3/Fitness/Controllers/HomeController.swift

**Comment by CameronHamidi** [comment]
Fixed in #157.
