### ISSUE TITLE
Fix OnboardingViewController layout

### ISSUE THREAD

**Issue by ywsang** [cuappdev/uplift-ios#149]
On smaller screens, Teagle Down gets cut off, and the arrows overlap the gym options. 

<img width="476" alt="Screen Shot 2019-09-04 at 4 42 48 PM" src="https://user-images.githubusercontent.com/20599510/64295012-2e1bb300-cf3e-11e9-9d88-343c45ee2425.png">

**Comment by ywsang** [comment]
@pnor this was addressed in your onboarding PR right?

**Comment by pnor** [comment]
Yup, issue should be fixed now
<img width="398" alt="image" src="https://user-images.githubusercontent.com/19177346/65009343-4692b280-d8da-11e9-8ba3-5a9c919065cd.png">
