### ISSUE TITLE
"Share" button in ClassDetailViewController is hard to see

### ISSUE THREAD

**Issue by CameronHamidi** [cuappdev/uplift-ios#163]
The "Share" button in the upper right corner of `ClassDetailViewController` is nearly impossible to see against the background of the class image, and is only visible after the user scrolls down.

![Simulator Screen Shot - iPhone 11 - 2019-09-25 at 16 37 48](https://user-images.githubusercontent.com/25390712/65637936-153d7500-dfb3-11e9-8bf5-9bbee7b76128.png)
![Simulator Screen Shot - iPhone 11 - 2019-09-25 at 16 37 53](https://user-images.githubusercontent.com/25390712/65637937-153d7500-dfb3-11e9-9d7c-2c43889d79fa.png)

Recommended to consult with design for a new icon.

**Comment by ywsang** [comment]
Looked into this -- looks like the dark share and light share icon we use are different style than the dark and light versions of the other icons. Will talk to design about this

**Comment by CameronHamidi** [comment]
The solution discussed with design, at least for these icons on the upper part of the class detail view, is to make them non sticky (i.e. have them subviews of the scroll view) and have them permanently white.
